[package]
name = "omg-idl"
version = "0.1.0"
authors = ["Adam C. Foltzer <acfoltzer@galois.com>"]
build = "build.rs"

[build-dependencies]
peg = "0.5"

[dependencies]
regex = "0.2"
lazy_static = "0.2"
